#ifndef DOG_COLLAR_STATE_MACHINE_H
#define DOG_COLLAR_STATE_MACHINE_H



typedef enum {
    DOG_COLLAR_STATE_INITIALIZING, 
    DOG_COLLAR_STATE_NORMAL,

    DOG_COLLAR_STATE_LOW_BATTERY,
    DOG_COLLAR_STATE_CHARGING,

    DOG_COLLAR_STATE_GPS_ACQUIRING,     
    DOG_COLLAR_STATE_GPS_READY,         
    DOG_COLLAR_STATE_GPS_TRACKING,      
    DOG_COLLAR_STATE_GPS_PAUSED,  
    
    DOG_COLLAR_STATE_WIFI_SYNC, 

    DOG_COLLAR_STATE_LIGHT_SLEEP,
    DOG_COLLAR_STATE_DEEP_SLEEP,

    DOG_COLLAR_STATE_ERROR
} dog_collar_state_t;











#endif // DOG_COLLAR_STATE_MACHINE_H